### ISSUE TITLE
implementation with KL-loss

### ISSUE THREAD

**Issue by xiaowei-ui** [yihui-he/KL-Loss#21] opened 2019-09-16 03:41 UTC
i want to know,do anyone have reproduced the code successfully? i want to apply the code into faster rcnn(tensorflow or pytorch),but i don't know how to do,looking forward to your recovery!

**Comment by ethanhe42** [comment] 2019-09-16 14:47
Duplicate of #20

**Closed as completed by ethanhe42** 2019-09-16 14:47 UTC

**Comment by LittleBoy7** [comment] 2019-09-23 08:01
@zhangliliang  Do you incorporated successfully?

**Comment by luckyxianxian** [comment] 2019-10-17 06:19
I would also like the pytorch version of the code very much and would appreciate it if the author could provide it
