### ISSUE TITLE
I can't find the part of kl-loss in this code..(I don't know anything about caffe)

### ISSUE THREAD

**Issue by xiaoqiang-cheng** [yihui-he/KL-Loss#26] opened 2019-10-28 14:20 UTC
Hi yihui-he,
    Could you point out this part(Kl-loss) for me?I want to change it to pytorch too. 
    You can email me(chengxq@tju.edu.cn).
Thank you.

**Comment by ethanhe42** [comment] 2019-10-28 16:51
Duplicate of #5

**Closed as completed by ethanhe42** 2019-10-28 16:51 UTC
